---
# Этот пакет отвечает за initdb опции. Ставим его и делаем необходимые нам настройки локалей и чек-сумм
- name: Force install postgresql-common
  apt:
    name: postgresql-common
    state: present
  notify: update_createcluster.conf

- name: Ensure PostgreSQL packages are installed.
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql-{{ postgres_version }}
    - libpq-dev
    - postgresql-contrib-{{ postgres_version }}
    - postgresql-{{ postgres_version }}-pg-wait-sampling
    - python3-psycopg2
    - postgresql-client-{{ postgres_version }}
    - postgresql-{{ postgres_version }}-pg-stat-kcache
    - nfs-client
