- name: restart postgres
  ansible.builtin.systemd:
    name: postgresql@{{ postgres_major_version }}-main.service
    state: restarted
  when: restart_postgres|default(omit) == true

- name: reload postgres
  ansible.builtin.systemd:
    name: postgresql@{{ postgres_major_version }}-main.service
    state: reloaded

- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: update nfs exports
  shell: /usr/sbin/exportfs -rav

- name: exec mount
  shell: |
    mount -a

- name: "start disable-transparent-huge-pages"
  systemd:
    name: "disable-transparent-huge-pages"
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2.service
    state: restarted
